import turtle
window=turtle.Screen()
window.bgcolor('navy')
window.setup(500,400)
window.title("Turtle")
window.delay(100000)
turtle=turtle.Turtle('turtle')
turtle.color('brown')
turtle.shapesize(3)
turtle.showturtle()
